### ISSUE TITLE
Query=format searches not working

### ISSUE THREAD

**Issue by hrzepa** [datacite/search#147]
https://search.datacite.org/works?query=format:chemical/x-cml works fine, but   https://search.datacite.org/works?query=format:chemical/x-c* returns no hits.

 https://search.datacite.org/works?query=format:chemical/x-mnova and https://search.datacite.org/works?query=format:chemical/x-mnpub should return hits (see http://data.datacite.org/10.14469/HPC/1280 ) but they do not. Nor does the generic https://search.datacite.org/works?query=format:chemical/x-m*

**Comment by mfenner** [comment]
Thanks @hrzepa, will look into this.

**Comment by hrzepa** [comment]
Martin,

"I am not clear what needs to be fixed or where there is a bug. Do you refer to the HTML presentation of this metadata record that you see at http://data.datacite.org/10.14469/HPC/1280 <http://data.datacite.org/10.14469/HPC/1280>? The nameIdentifierScheme is not displayed and we should add that.”

Yes Martin, it is the "nameIdentifierScheme is not displayed" that was our issue.  The “human readable” presentation does not make clear that it is an  ORCID that is being displayed.  It would also be good to have the identifier hyperlinked to the  ORCID.

Henry

PS Will you be attending  http://pidapalooza.org/ <http://pidapalooza.org/> ?

**Comment by mfenner** [comment]
Yes, I will go to http://pidapalooza.org.

**Comment by richardhallett** [comment]
Hello, this is an old issue but we've changed the underlying way all our search stuff happens in the last year.
Please see some of our updated documentation: 
https://support.datacite.org/docs/datacite-search-user-documentation
And our blog post announcing our new search: https://blog.datacite.org/improving-search/

It's difficult to re-create exactly the original problem due to the fact the search has changed and also by the looks of it some of the metadata surrounding the examples
However as an example you can query for formats like:
https://search.datacite.org/works?query=formats%3Achemical%2Fx-cml

I'm closing this, but if there is further comment or examples please let us know.
