### ISSUE TITLE
OAI-PMH error when fetching data from 1001st

### ISSUE THREAD

**Issue by fumi** [datacite/search#173]
OAI-PMH returns a 500 error when a program tries to fetch data from 1001st as completeListSize is more than 1000. The following url shows an error example. 

https://oai.datacite.org/oai?resumptionToken=1548828515256%2C2019-01-28T00%3A00%3A00Z%2C2019-01-28T23%3A59%3A59Z%2C1000%2Cnull%2Coai_datacite&verb=ListRecords

**Comment by kjgarza** [comment]
fixed in: https://github.com/datacite/search/commit/fc953ced5e2ef6ea59716c8e4755bddf2f4c626e

**Comment by fumi** [comment]
@kjgarza 
Thanks for fixing this. However the number of records on 29 Jan. 2019 is 157883 unfortunately.  The limit should be increased more.

**Comment by kjgarza** [comment]
@fumi unfortunately we have been limitting this for performance issues. We will replace the service and have full functionaility soon as we working on improve the backend. Follow this ticket for details on that https://github.com/datacite/datacite/issues/642 .

One question, are you harvesting all DataCite DOIs or are you only interested in the ones from your datacenter ?

**Comment by fumi** [comment]
Currently we harvest all DataCite DOIs on a daily basis.

**Comment by richardhallett** [comment]
As @kjgarza mentioned we currently limit OAI due to the solr implementation, you can potentially instead use our new REST API see pagination docs here: https://support.datacite.org/docs/pagination

As the original problem was fixed, the overall next best solution is https://github.com/datacite/datacite/issues/642 so closing this issue.

Many thanks for the information about your usage as well.
